mysql:
  image: mariadb:10.1.22
  container_name: core_mariadb
  environment:
    MYSQL_DATABASE: core_app
    MYSQL_ROOT_PASSWORD: 123456
  volumes:
    - ./database/mariadb:/var/lib/mysql
  ports:
    - 3306:3306

php:
  build: .
  dockerfile: ./docker-conf/php/Dockerfile
  container_name: core_php
  volumes:
    - .:/home/core/app

nginx:
  image: nginx:1.10.3
  container_name: core_nginx
  volumes_from:
    - php
  volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 80:80

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  container_name: core_phpmyadmin
  links:
    - mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 123456
    PMA_HOST: mysql
